# Commented until CodeClimate Platform plays
# as nice as Classic
#
# engines:
#   rubocop:
#     enabled: true
# 
# ratings:
#   paths:
#   - lib/**
#   - "**.rb"

languages:
  Ruby: true

exclude_paths:
- spec/**/*
